// Code generated by Kitex v0.0.5. DO NOT EDIT.

package facade

import (
	"context"
	"github.com/ameidance/paster_facade/model/vo/kitex_gen/paster/facade"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/kitex/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetPost(ctx context.Context, Req *facade.GetPostRequest, callOptions ...callopt.Option) (r *facade.GetPostResponse, err error)
	SavePost(ctx context.Context, Req *facade.SavePostRequest, callOptions ...callopt.Option) (r *facade.SavePostResponse, err error)
	GetComments(ctx context.Context, Req *facade.GetCommentsRequest, callOptions ...callopt.Option) (r *facade.GetCommentsResponse, err error)
	SaveComment(ctx context.Context, Req *facade.SaveCommentRequest, callOptions ...callopt.Option) (r *facade.SaveCommentResponse, err error)
	Check(ctx context.Context, Req *facade.HealthCheckRequest, callOptions ...callopt.Option) (r *facade.HealthCheckResponse, err error)
	Watch(ctx context.Context, Req *facade.HealthCheckRequest, callOptions ...callopt.Option) (stream Facade_WatchClient, err error)
}

type Facade_WatchClient interface {
	streaming.Stream
	Recv() (*facade.HealthCheckResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFacadeClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFacadeClient struct {
	*kClient
}

func (p *kFacadeClient) GetPost(ctx context.Context, Req *facade.GetPostRequest, callOptions ...callopt.Option) (r *facade.GetPostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPost(ctx, Req)
}

func (p *kFacadeClient) SavePost(ctx context.Context, Req *facade.SavePostRequest, callOptions ...callopt.Option) (r *facade.SavePostResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SavePost(ctx, Req)
}

func (p *kFacadeClient) GetComments(ctx context.Context, Req *facade.GetCommentsRequest, callOptions ...callopt.Option) (r *facade.GetCommentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetComments(ctx, Req)
}

func (p *kFacadeClient) SaveComment(ctx context.Context, Req *facade.SaveCommentRequest, callOptions ...callopt.Option) (r *facade.SaveCommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveComment(ctx, Req)
}

func (p *kFacadeClient) Check(ctx context.Context, Req *facade.HealthCheckRequest, callOptions ...callopt.Option) (r *facade.HealthCheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Check(ctx, Req)
}

func (p *kFacadeClient) Watch(ctx context.Context, Req *facade.HealthCheckRequest, callOptions ...callopt.Option) (stream Facade_WatchClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Watch(ctx, Req)
}
